import type { DashboardConfig } from '../types/widget.types';

export const defaultDashboardConfig: DashboardConfig = {
  columns: 3,
  widgets: [
    {
      id: 'stats-revenue',
      type: 'stats',
      title: 'Total Revenue',
      value: '$45,231',
      change: 12.5,
      changeLabel: 'from last month',
      icon: '💰',
      height: 2,
      width: 1,
      order: 1,
    },
    {
      id: 'stats-users',
      type: 'stats',
      title: 'Active Users',
      value: '2,543',
      change: 8.2,
      changeLabel: 'from last week',
      icon: '👥',
      height: 2,
      width: 1,
      order: 2,
    },
    {
      id: 'stats-conversion',
      type: 'stats',
      title: 'Conversion Rate',
      value: '3.24%',
      change: -2.1,
      changeLabel: 'from yesterday',
      icon: '📊',
      height: 2,
      width: 1,
      order: 3,
    },
    {
      id: 'activity-feed',
      type: 'activity',
      title: 'Recent Activity',
      height: 4,
      width: 2,
      order: 4,
      items: [
        {
          id: '1',
          title: 'New user registration completed',
          timestamp: '2 minutes ago',
          type: 'success',
        },
        {
          id: '2',
          title: 'Payment received from client',
          timestamp: '15 minutes ago',
          type: 'success',
        },
        {
          id: '3',
          title: 'Server response time increased',
          timestamp: '1 hour ago',
          type: 'warning',
        },
        {
          id: '4',
          title: 'Database backup completed',
          timestamp: '2 hours ago',
          type: 'info',
        },
        {
          id: '5',
          title: 'Failed login attempt detected',
          timestamp: '3 hours ago',
          type: 'error',
        },
      ],
    },
    {
      id: 'progress-tasks',
      type: 'progress',
      title: 'Project Progress',
      height: 4,
      width: 1,
      order: 5,
      tasks: [
        {
          id: '1',
          label: 'Design System',
          progress: 100,
          status: 'completed',
        },
        {
          id: '2',
          label: 'Frontend Development',
          progress: 75,
          status: 'active',
        },
        {
          id: '3',
          label: 'Backend API',
          progress: 60,
          status: 'active',
        },
        {
          id: '4',
          label: 'Testing & QA',
          progress: 30,
          status: 'active',
        },
        {
          id: '5',
          label: 'Documentation',
          progress: 0,
          status: 'pending',
        },
      ],
    },
  ],
};
