@startuml
title TechVibe sequences

actor User

participant Frontend
participant Api
participant New <<queue>>
participant Downloader
participant Downloaded <<queue>>
participant SpeechToText
participant Transcribed <<queue>>
participant NLP


database "Azure Blob Storage" as Storage

User -> Frontend : inserts the video link
Frontend -> Api : POST
Api -> Storage : new metadata
Api -> New : send message
Api -> Frontend : 201 'Created'
Downloader --> New : read message
Downloader -> Downloaded : send message
SpeechToText --> Downloaded : read message
SpeechToText -> Transcribed : send message
NLP --> Transcribed : read message
NLP -> Storage : save result

Frontend -> Api : GET
Api --> Storage : read result+metadata
Api -> Frontend : send result
Frontend -> User : show the result


@enduml