@startuml
title TechVibe sequences

actor User

participant Api
queue New
participant Downloader
queue Downloaded
participant SpeechToText
queue Transcribed
participant NLP


database Storage

User -> Api : POST
Api -> Storage : new metadata
Api -> New : send message
Api -> User : 201 'Created'
Downloader --> New : read message
Downloader -> Downloaded : send message
SpeechToText --> Downloaded : read message
SpeechToText -> Transcribed : send message
NLP --> Transcribed : read message
NLP -> Storage : save result

User -> Api : GET
Api --> Storage : read result+metadata
Api -> User : send result



@enduml