name: Backend CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect backend changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
  skip-if-no-changes:
    runs-on: ubuntu-latest
    name: No changes detected
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'false'
    steps:
      - run: echo "No changes detected, skipping backend pipeline"
      
  changes-lint-job-dummy:
    runs-on: ubuntu-latest
    name: Lint
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - name: Lint code
        run: npm run lint --if-present