# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    # restore dependencies only if package-lock.json changed
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
     
    - name: Build app
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@4
      with:
        name: frontend-build
        path: frontend/dist
        retention-days: 1
  
  lint:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
      
      - name: Lint code
        run: npm run lint --if-present
        
  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
      
      - name: Run tests
        run: npm test --if-present -- --coverage
  # Ensure that the app can actually start
  smoke:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
      - name: Run smoke test
        run: |
          npm run preview &
          sleep 5
          curl -f http://localhost:5173 || exit 1
    
