name: Generate PlantUML Diagrams

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate diagrams in place using PlantUML Docker
        run: |
          # find all .puml files and render them in place
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            plantuml/plantuml \
            -tpng \
            -o . \
            $(find /workspace -name '*.puml')

      - name: Upload generated diagrams as artifact
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-diagrams
          path: '**/*.png'

      - name: Commit and push generated diagrams
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '**/*.png'
          git commit -m "chore: update PlantUML diagrams [skip ci]" || echo "No changes to commit"
          git push
