name: Generate PlantUML Diagrams

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List .puml files
        run: |
          echo "Checking for .puml files:"
          find . -type f -name "*.puml" || echo "No .puml files found!"
          
      - name: Generate diagrams in place using PlantUML Docker
        run: |
          echo "Running PlantUML inside Docker..."
          docker run --rm \
            -v "$PWD:/data" \
            -w /data \
            plantuml/plantuml \
            -tpng -o . $(find . -type f -name "*.puml")

          echo "Listing generated PNGs:"
          find . -type f -name "*.png" || echo "No PNG files generated!"

      - name: Upload diagrams
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-diagrams
          path: |
            ./**/*.png
          if-no-files-found: warn

            - name: Publish diagrams to Wiki
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Publishing diagrams to Wiki..."

          # Authenticated URL
          REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git"

          # Prepare wiki directory
          mkdir wiki
          cd wiki

          # Clone the wiki repository
          git clone "$REPO_URL" .
          
          # Configure git identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config credential.helper store

          # Disable any interactive credential prompts
          git config --global credential.helper 'store'
          git config --global advice.detachedHead false

          # Ensure target folder exists
          mkdir -p diagrams

          # Copy generated PNG diagrams
          shopt -s globstar
          find ../ -type f -name "*.png" -exec cp {} diagrams/ \; || echo "No diagrams found to copy."

          echo "Copied diagrams:"
          ls -l diagrams || echo "No diagrams directory content."

          # Commit and push changes
          git add diagrams/ || true
          git commit -m "Update PlantUML diagrams [skip ci]" || echo "No changes to commit"

          # Explicitly set remote URL with token to avoid credential issues
          git remote set-url origin "$REPO_URL"

          git push origin master || echo "No wiki push needed"

