name: Generate PlantUML Diagrams

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List .puml files
        run: |
          echo "Checking for .puml files:"
          find . -type f -name "*.puml" || echo "No .puml files found!"
          
      - name: Generate diagrams in place using PlantUML Docker
        run: |
          echo "Running PlantUML inside Docker..."
          docker run --rm \
            -v "$PWD:/data" \
            -w /data \
            plantuml/plantuml \
            -tpng -o . $(find . -type f -name "*.puml")

          echo "Listing generated PNGs:"
          find . -type f -name "*.png" || echo "No PNG files generated!"

      - name: Upload diagrams
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-diagrams
          path: |
            ./**/*.png
          if-no-files-found: warn

      - name: Push generated diagrams to Wiki
        if: always()
        run: |
          echo "Publishing diagrams to Wiki..."

          # Extract repo information
          REPO_URL="https://github.com/${{ github.repository }}.wiki.git"

          # Prepare temp dir for wiki
          mkdir wiki
          cd wiki

          # Clone the wiki repo
          git clone "$REPO_URL" .
          
          # Configure bot identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure target folder exists
          mkdir -p diagrams

          # Copy diagrams from repo root (two levels up) into wiki folder
          shopt -s globstar
          find ../ -type f -name "*.png" -exec cp {} diagrams/ \; || echo "No diagrams found to copy."

          echo "Copied diagrams:"
          ls -l diagrams || echo "No diagrams directory content."

          # Commit and push changes
          git add diagrams/ || true
          git commit -m "Update PlantUML diagrams [skip ci]" || echo "No changes to commit"
          git push origin master || echo "No wiki push needed"
