name: Generate PlantUML Diagrams

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List .puml files
        run: |
          echo "Checking for .puml files:"
          find . -type f -name "*.puml" || echo "No .puml files found!"
          
      - name: Generate diagrams in place using PlantUML Docker
        run: |
          echo "Running PlantUML inside Docker..."
          docker run --rm \
            -v "$PWD:/data" \
            -w /data \
            plantuml/plantuml \
            -tpng -o . $(find . -type f -name "*.puml")
          echo "Listing generated PNGs:"
          find . -type f -name "*.png" || echo "No PNG files generated!"
      - name: Upload diagrams
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-diagrams
          path: |
            ./**/*.png
          if-no-files-found: warn

      - name: Commit and push generated diagrams
        if: github.event_name == 'pull_request'
        run: |
          BRANCH_NAME="main"
          echo "Committing diagrams back to branch: $BRANCH_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin $BRANCH_NAME
          git checkout $BRANCH_NAME
          git add './*.png'
          git commit -m "chore: update PlantUML diagrams [skip ci]" || echo "No changes to commit"
          git push -f origin HEAD:$BRANCH_NAME